// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     block.schema.v1.asvc
 *     pendingtx.schema.v1.asvc
 */

package models

type UnionNullInt struct {
	Null      interface{}
	Int       int32
	UnionType UnionNullIntTypeEnum
}

type UnionNullIntTypeEnum int

const (
	UnionNullIntTypeEnumNull UnionNullIntTypeEnum = 0
	UnionNullIntTypeEnumInt  UnionNullIntTypeEnum = 1
)
