// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     schemas.asvc
 */

package ethvm

import (
	"io"
)

type Log struct {
	Address string
	Topics  [][]byte
	Data    []byte
	Removed bool
}

func DeserializeLog(r io.Reader) (*Log, error) {
	return readLog(r)
}

func NewLog() *Log {
	v := &Log{
		Topics: make([][]byte, 0),
	}

	return v
}

func (r *Log) Schema() string {
	return "{\"fields\":[{\"desc\":\"\",\"name\":\"address\",\"type\":\"string\"},{\"desc\":\"\",\"name\":\"topics\",\"type\":{\"items\":\"bytes\",\"type\":\"array\"}},{\"desc\":\"\",\"name\":\"data\",\"type\":\"bytes\"},{\"desc\":\"\",\"name\":\"removed\",\"type\":\"boolean\"}],\"name\":\"Log\",\"namespace\":\"io.enkrypt.bolt.avro\",\"type\":\"record\"}"
}

func (r *Log) Serialize(w io.Writer) error {
	return writeLog(r, w)
}
